### ISSUE TITLE
Cannot Open Swagger-UI and http://localhost:8080

### ISSUE THREAD

**Issue by BaiGeiQiShi** [SelimHorri/project-tracking-system-backend-app#51]
Thanks for making this Project!

I'm interested in using this Project for a test. I followed the instructions in README.md to have the Project installed. After I started the Spring Boot server, I couldn't open the swagger-ui and http://localhost:8080. But I can enter other pages.

1.Swagger-ui
![image](https://user-images.githubusercontent.com/67951843/147934421-65da7411-ad4d-4c99-bf83-efed00adea5e.png)
2.localhost
![image](https://user-images.githubusercontent.com/67951843/147934390-e3e7571e-9e42-4dfd-b83c-7841a5d005c1.png)
3.Admin
![image](https://user-images.githubusercontent.com/67951843/147934313-5815a1f3-844d-402b-a21d-3498568dc9c5.png)
I don't know how to fix it. Could you help me? Thanks in advance!

**Comment by SelimHorri** [comment]
Hi @BaiGeiQiShi,
Thanks for your concerns about this project, i appreciate...
Actually, the entrypoint of the app should be with "http://localhost:8080/app", not "http://localhost:8080/". Indeed, Swagger UI should be at "http://localhost:8080/app/swagger-ui.html" 
Please note that Swagger is available only when deploying the application in **_dev_** env (which is by default) or **_test_** env
Happy coding 😊

**Comment by BaiGeiQiShi** [comment]
Hi @SelimHorri,
Thanks very much for your reply! This is my fault. I missed `/app`. It now works for me.

**Comment by Naidurella** [comment]
Hello sir, could please me tell me the credentials of the employee, manager and admin. please sir

**Comment by SelimHorri** [comment]
Hi @Naidurella ,
Hope this find you.
For testing purposes, you can login with a '0000' password in dev (default) or test environments with specified username, based on the role (employee, manager or admin)
Enjoy ;)
